### ISSUE TITLE
Feature: Context aware Entry Create Page

### ISSUE THREAD

**Issue by lumjjb** [lumjjb/tornjak#28]
# Feature: Context aware Entry Create Page

This feature is an Epic which consists of improvements to the Entry Create page. The goal of this is to assist in the creation of entries with context known from the SPIRE server configuration and APIs as well as user provided information.

These goals can be illustrated by the following processes:
- Spiffe IDs create can only below to the trust-domain, thus the field should be pre-populated
- Parent IDs would mostly be based on current agent entries or the SPIRE server ID itself, this should be selectable or recommended
- Each SPIRE server and their agents are configured with node and workload attestors. These attestors have a set of possible selectors. These selectors can be recommended and validated based on configuration - e.g. using `k8s_psat`, recommend `k8s_psat:cluster:`, etc.

In addition to this, the epic also includes general improvements to the form.

# Scope of feature

This work will include
- [x] Adding full API expressiveness in UI for Entry Create
- [x] Providing auto-fill and restriction of trust domain for SPIFFE ID fields
- [x] Enable populating and recommending agent and spire server as parent IDs
  - [x] Enable obtaining list of agent and spire server spiffe ID derivation
  - [x] Providing recommendation/dropdown of possible servers
- [x] Selectors recommendation by the parentID selected
  - [x] Create ability to obtain selector information based on tornjak serverinfo
  - [x] Provide a way to define workload attestor information
  - [x] Create selector recommendations based on attestors

# Details of feature items

Below details additional information and context for the feature items above. For reference, the existing entry create form looks like the following:

![image](https://user-images.githubusercontent.com/3060102/113456603-a6c54880-93db-11eb-984b-6669d2874d27.png)

## Adding full API expressiveness in UI for Entry Create

Currently, the UI API only allows specifying SPIFFE ID, parent ID, selectors and Admin flag. This is only a subset of the allowed API in https://github.com/spiffe/spire/blob/v0.12.0/proto/spire/types/entry.pb.go#L28-L67

## Providing auto-fill and restriction of trust domain for SPIFFE ID fields

The trust domain is specified by the trust domain of the SPIRE server, the Trust domain should be populated and restricted in the SPIFFE ID field to assist filling up the form.

## Enable populating and recommending agent and spire server as parent IDs

The parentIDs should be usually based on existing entries/agents or the default spire server (spiffe://<trust domain>/spire/server).

### Enable obtaining list of agent and spire server spiffe ID derivation

Entry list should utilize the list of agents and the default spire server (to mimic the `-node` CLI flag). This should be retrieved and stored probably within the redux framework, and updated when refreshed or on detectable change.

### Providing recommendation/dropdown of possible servers

The stored list should be used to provide options for selection in the parentID. but still allow free form (because of eventual consistency model). This should not be restricted to just a dropdown because it is possible to be able to create entry for non-existent parent IDs if following the eventual consistency model. 

## Selectors recommendation by the parentID selected

Selectors should be recommended based on the server and agent configuration. The scope of this should be existing upstreamed node attestors and workload attestors in the docs folder (https://github.com/spiffe/spire/tree/master/doc). A current limitation of SPIRE agents are that they do not expose plugin information. It is not in scope of this feature to implement exposing that information. Instead, it will be based on operator configuration, which is how it is done today. An exception for this is SPIRE server plugins since the tornjak agent has access to this information via the tornjak serverinfo API.

### Create ability to obtain selector information based on tornjak serverinfo

Tornjak serverinfo provides the configuration of the SPIRE server where the tornjak agent resides. Using this information can provide knowledge of the selectors used. 

### Provide a way to define workload attestor information

Since workload attestors are only configured on agents, and there is no API to provide agent configuration, a side requirement here is to allow the operator to specify the workload attestor during create or to add it post-creation. An operator should be able to define annotations of the workload selectors used per agent at or post creation time. This can then be used later on for visibility and recommendation of selectors.

### Create selector recommendations based on attestors

Based on the selection of Parent ID, it should be able to be determined by the attestor information which are possible selectors for each plugin. These should come out as recommendations for the entry form.

**Comment by mamy-CS** [comment]
When removing "Is_Manager" consider file "tornjak-api-helpers.js"
